src/HoyryStats/Controllers/SteamAchievementsController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using HoyryStats.Models;

namespace HoyryStats.Controllers
{
    public class SteamAchievementsController : Controller
    {
        private ApplicationDbContext _context;

        public SteamAchievementsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: SteamAchievements
        public IActionResult Index()
        {
            return View(_context.SteamAchievement.ToList());
        }

        // GET: SteamAchievements/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            SteamAchievement steamAchievement = _context.SteamAchievement.Single(m => m.ID == id);
            if (steamAchievement == null)
            {
                return HttpNotFound();
            }

            return View(steamAchievement);
        }

        // GET: SteamAchievements/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SteamAchievements/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SteamAchievement steamAchievement)
        {
            if (ModelState.IsValid)
            {
                _context.SteamAchievement.Add(steamAchievement);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(steamAchievement);
        }

        // GET: SteamAchievements/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            SteamAchievement steamAchievement = _context.SteamAchievement.Single(m => m.ID == id);
            if (steamAchievement == null)
            {
                return HttpNotFound();
            }
            return View(steamAchievement);
        }

        // POST: SteamAchievements/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(SteamAchievement steamAchievement)
        {
            if (ModelState.IsValid)
            {
                _context.Update(steamAchievement);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(steamAchievement);
        }

        // GET: SteamAchievements/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            SteamAchievement steamAchievement = _context.SteamAchievement.Single(m => m.ID == id);
            if (steamAchievement == null)
            {
                return HttpNotFound();
            }

            return View(steamAchievement);
        }

        // POST: SteamAchievements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            SteamAchievement steamAchievement = _context.SteamAchievement.Single(m => m.ID == id);
            _context.SteamAchievement.Remove(steamAchievement);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/HoyryStats/Controllers/SteamNewsItemsController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using HoyryStats.Models;
using System.Threading.Tasks;
using System.Net.Http;
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace HoyryStats.Controllers
{
    public class SteamNewsItemsController : Controller
    {
        private ApplicationDbContext _context;

        public SteamNewsItemsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SteamNewsItems
        public IActionResult Index()
        {
            return View(_context.SteamNewsItem.ToList());
        }

        // GET: SteamNewsItems/Details/5
        public IActionResult Details(string id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            SteamNewsItem steamNewsItem = _context.SteamNewsItem.Single(m => m.ID == id);
            if (steamNewsItem == null)
            {
                return HttpNotFound();
            }

            return View(steamNewsItem);
        }

        // GET: SteamNewsItems/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SteamNewsItems/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SteamNewsItem steamNewsItem)
        {
            if (ModelState.IsValid)
            {
                _context.SteamNewsItem.Add(steamNewsItem);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(steamNewsItem);
        }

        // GET: SteamNewsItems/Edit/5
        public IActionResult Edit(string id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            SteamNewsItem steamNewsItem = _context.SteamNewsItem.Single(m => m.ID == id);
            if (steamNewsItem == null)
            {
                return HttpNotFound();
            }
            return View(steamNewsItem);
        }

        // POST: SteamNewsItems/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(SteamNewsItem steamNewsItem)
        {
            if (ModelState.IsValid)
            {
                _context.Update(steamNewsItem);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(steamNewsItem);
        }

        // GET: SteamNewsItems/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(string id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            SteamNewsItem steamNewsItem = _context.SteamNewsItem.Single(m => m.ID == id);
            if (steamNewsItem == null)
            {
                return HttpNotFound();
            }

            return View(steamNewsItem);
        }

        // POST: SteamNewsItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(string id)
        {
            SteamNewsItem steamNewsItem = _context.SteamNewsItem.Single(m => m.ID == id);
            _context.SteamNewsItem.Remove(steamNewsItem);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        #region Helper Methods


        #endregion
    }
}

src/HoyryStats/Controllers/SteamPlayersController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using HoyryStats.Models;
using System.Net.Http;
using System;
using Newtonsoft.Json;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;

namespace HoyryStats.Controllers
{
    public class SteamPlayersController : Controller
    {
        private ApplicationDbContext _context;
        private readonly ILogger<SteamPlayersController> _logger;

        public SteamPlayersController(ApplicationDbContext context, ILogger<SteamPlayersController> logger)
        {
            _context = context;
            _logger = logger;
        }

        // GET: SteamPlayers
        public IActionResult Index()
        {
            _logger.LogInformation(_context.SteamPlayer.First().Id.ToString());
            return View(_context.SteamPlayer.ToList());
        }

        // GET: SteamPlayers/Details/5
        public IActionResult Details(long? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            SteamPlayer steamPlayer = _context.SteamPlayer.Single(m => m.Id == id);
            if (steamPlayer == null)
            {
                return HttpNotFound();
            }

            return View(steamPlayer);
        }

        // GET: SteamPlayers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SteamPlayers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SteamPlayer steamPlayer)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    SteamPlayer player = GetPlayerData(Constants.ApiKey, steamPlayer.Id);
                    player.playerGames = GetPlayerGames(Constants.ApiKey, steamPlayer.Id);
                    player.playerFriends = GetPlayerFriends(Constants.ApiKey, steamPlayer.Id);
                    foreach (var game in player.playerGames)
                    {
                        player.playerStats = GetPlayerAchievements(Constants.ApiKey, steamPlayer.Id, game.game);
                        UpdatePlayersGamesToDatabase(Constants.ApiKey, game.game, steamPlayer.Id);
                    }
                    _context.SteamPlayer.Add(player);
                    _context.SaveChanges();

                }
                catch(Exception ex)
                {
                    _logger.LogError(ex.Message + " " + ex.InnerException);
                }
                return RedirectToAction("Index");
            }
            return View(steamPlayer);
        }





        // GET: SteamPlayers/Edit/5
        public IActionResult Edit(long? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            SteamPlayer steamPlayer = _context.SteamPlayer.Single(m => m.Id == id);
            if (steamPlayer == null)
            {
                return HttpNotFound();
            }
            return View(steamPlayer);
        }

        // POST: SteamPlayers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(SteamPlayer steamPlayer)
        {
            if (ModelState.IsValid)
            {
                _context.Update(steamPlayer);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(steamPlayer);
        }

        // GET: SteamPlayers/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(long? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            SteamPlayer steamPlayer = _context.SteamPlayer.Single(m => m.Id == id);
            if (steamPlayer == null)
            {
                return HttpNotFound();
            }

            return View(steamPlayer);
        }

        // POST: SteamPlayers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(long id)
        {
            SteamPlayer steamPlayer = _context.SteamPlayer.Single(m => m.Id == id);
            _context.SteamPlayer.Remove(steamPlayer);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        #region helper methods
        private SteamPlayer GetPlayerData(string apikey, long id)
        {
            using (var client = new HttpClient())
            {
                var uri = new Uri("http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=" + Constants.ApiKey + "&steamids=" + id);
                var response = client.GetAsync(uri).Result;
                var result = response.Content.ReadAsStringAsync().Result;
                PlayerRoot playerRoot = JsonConvert.DeserializeObject<PlayerRoot>(result);
                SteamPlayer player = playerRoot.response.players.SingleOrDefault();
                return player;
            }
        }

        private List<PlayersGameModel> GetPlayerGames(string apikey, long id)
        {
            List<PlayersGameModel> games = new List<PlayersGameModel>();
            using (var client = new HttpClient())
            {
                var uri = new Uri("http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key="+Constants.ApiKey+"&steamid="+id+"&format=json");
                var response = client.GetAsync(uri).Result;
                var result = response.Content.ReadAsStringAsync().Result;
                PlayerGameRoot gameRoot = JsonConvert.DeserializeObject<PlayerGameRoot>(result);
                games = gameRoot.response.games;

            }
            return games;
        }

        private List<SteamPlayerFriend> GetPlayerFriends(string apikey, long id)
        {
            List<SteamPlayerFriend> friends = new List<SteamPlayerFriend>();
            using (var client = new HttpClient())
            {
                var uri = new Uri("http://api.steampowered.com/ISteamUser/GetFriendList/v0001/?key="+apikey+"&steamid="+id+"&relationship=friend");
                var response = client.GetAsync(uri).Result;
                var result = response.Content.ReadAsStringAsync().Result;
                FriendRoot friendsRoot = JsonConvert.DeserializeObject<FriendRoot>(result);
                friends = friendsRoot.friendslist.friends;
                return friends;
            }
        }

        private PlayerStats GetPlayerAchievements(string apikey, long id, int appid)
        {
            using (var client = new HttpClient())
            {
                var uri = new Uri("http://api.steampowered.com/ISteamUserStats/GetPlayerAchievements/v0001/?appid="+appid+"&key="+ apikey + "&steamid="+id);
                var response = client.GetAsync(uri).Result;
                var result = response.Content.ReadAsStringAsync().Result;
                PlayerAchievementRoot achievementRoot = JsonConvert.DeserializeObject<PlayerAchievementRoot>(result);
                return achievementRoot.playerstats;
            }
        }

        private void UpdatePlayersGamesToDatabase(string apikey, int appid, long playerId)
        {
            using (var client = new HttpClient())
            {
                try
                {
                    var uri = new Uri("http://api.steampowered.com/ISteamUserStats/GetSchemaForGame/v2/?key="+ apikey + "&appid=" + appid);
                    var response = client.GetAsync(uri).Result;
                    if (response.Content != null)
                    {
                        var result = response.Content.ReadAsStringAsync().Result;
                        if (!string.IsNullOrEmpty(result))
                        {
                            SteamGameRoot achievementRoot = JsonConvert.DeserializeObject<SteamGameRoot>(result);
                            if (achievementRoot != null && achievementRoot.game != null)
                            {
                                AvailableGameStats tempStat = new AvailableGameStats();
                                SteamGame tempGame = new SteamGame();
                                List<SteamGameAchievement> tempAchis = new List<SteamGameAchievement>();
                                List<SteamGameDefaultStats> tempStats = new List<SteamGameDefaultStats>();

                                if (
                                    achievementRoot.game.availableGameStats != null
                                    && achievementRoot.game.availableGameStats.achievements != null
                                    && achievementRoot.game.availableGameStats.stats != null
                                    && achievementRoot.game.availableGameStats.achievements.Count != 0
                                    && achievementRoot.game.availableGameStats.stats.Count != 0)
                                {
                                    tempGame = achievementRoot.game;
                                    tempStat = achievementRoot.game.availableGameStats;
                                    foreach (var achi in achievementRoot.game.availableGameStats.achievements)
                                    {
                                        if (achi.displayName != null && achi.description != null)
                                        {
                                            tempAchis.Add(achi);
                                        }
                                    }
                                    foreach (var stat in achievementRoot.game.availableGameStats.stats)
                                    {
                                        if (stat.displayname != null && stat.name != null)
                                        {
                                            tempStats.Add(stat);
                                        }
                                    }
                                    try

src/HoyryStats/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - HoyryStats</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/material-design-lite/material.css" />
            <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.blue-light_green.min.css" />
            <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
            <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
            <link rel="stylesheet" href="~/css/hoyry.css" />
            <script src="~/lib/material-design-lite/material.js"></script>
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
            <script src="~/js/background.js"></script>
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="~/css/hoyry.min.css" asp-append-version="true" />
            <link rel="stylesheet" href="~/lib/material-design-lite/material.min.css" />
            <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.blue-light_green.min.css" />
            <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
            <script src="~/lib/material-design-lite/material.js"></script>
            <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="~/js/background.js"></script>
        </environment>
    </head>
<body>
    <canvas id="c"></canvas>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="mdl-layout__header">
            @Html.Partial("_LayoutHeader")
        </header>
        @Html.Partial("_SideNavigation")
        <main class="mdl-layout__content">
            <div class="main-data-container">
                @RenderBody()
            </div>
        </main>
        <footer id="hoyry-footer" class="mdl-mini-footer">
            @Html.Partial("_LayoutFooter")
        </footer>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>

src/HoyryStats/Views/Shared/_LayoutFooter.cshtml
<div class="mdl-mini-footer__left-section">
    <div class="mdl-logo">Höyry</div>
    <ul class="mdl-mini-footer__link-list">
        <li><a href="http://steampowered.com">Powered by Steam</a></li>
    </ul>
</div>

src/HoyryStats/Views/Shared/_LayoutHeader.cshtml
@using System.Security.Claims
<div id="hoyry-header" class="mdl-layout__header-row">
    <!--Settings Modal-->
    <div class="header-modal-square">
        @if (User.IsSignedIn())
        {
            var user = User;
            string lol = "";
            <div id="playerProfileCircle"></div>
        }
        else
        {

            <div class="square-container">
                <a asp-controller="Account" asp-action="Login">
                    <i class="fa fa-4x fa-sign-in"></i>
                </a>
            </div>
        }
    </div>
    <!-- Title -->
    <a id="header-title" asp-controller="Home" asp-action="Index" class="mdl-layout-title archive-font"><span>Höyry</span></a>
</div>
<script>
    function LogOff() {
        $('#logoutForm').submit();
    }
</script>

src/HoyryStats/Views/Shared/_SideNavigation.cshtml
@using System.Security.Claims

<div id="hoyry-sidenav" class="sidenav">
    @if (User.IsSignedIn())
    {
        <div class="sidemenu-item">
            <a asp-controller="SteamPlayers" asp-action="Index">Players</a>
        </div>
        <div class="sidemenu-item">
            <a asp-controller="SteamNewsItems" asp-action="Index">News</a>
        </div>
        <div class="sidemenu-item">
            <a asp-controller="SteamAchievements" asp-action="Index">Achievements</a>
        </div>
    }
    else
    {
        <div id="signin-animation-container" class="animated bounce">
            <i class="fa fa-3x fa-arrow-up"></i>
            <p>Sign in!</p>
        </div>
    }
</div>